### ISSUE TITLE
Add support for setting/updating zpool properties (e.g. ashift, autoexpand)

### ISSUE THREAD

**Issue by exterrestris** [mrlesmithjr/ansible-zfs#29]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to specify non-default zpool properties (e.g. to force a specific ashift, or enable auto expand) when creating a zpool, and to update those properties if changed

**Describe the solution you'd like**
Specifying properties in an intuitive manner, along the lines of:
```yaml
zfs_pools:
  - pool1
    properties:
      ashift: '12'
      autoexpand: 'on'

```

**Describe alternatives you've considered**
The existing (undocumented) `options` property does partially allow for this (on pool creation only), but requires a non-intutive syntax and knowledge of `zpool` command options. Equivalent of above:
```yaml
zfs_pools:
  - pool1
    options:
      - '-o ashift=12'
      - '-o autoexpand=on'

```

**Additional context**
n/a
